CREATE TYPE "product_status" AS ENUM (
  'in_stock',
  'out_of_stock',
  'running_low'
);

CREATE TYPE "order_status" AS ENUM (
  'placed',
  'confirmed',
  'processed',
  'delivered'
);

CREATE TABLE "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "serial" varchar,
  "name" varchar(100),
  "merchant_id" int,
  "price" float(8,2),
  "status" product_status,
  "stock" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "merchant" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150),
  "country_id" in,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "country" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150)
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" order_status,
  "user_id" int,
  "total" float(12,2),
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int
);

ALTER TABLE "product" ADD FOREIGN KEY ("merchant_id") REFERENCES "merchant" ("id");

ALTER TABLE "merchant" ADD FOREIGN KEY ("country_id") REFERENCES "country" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");
