CREATE TYPE "user_status" AS ENUM (
  'banned',
  'active',
  'inactive'
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(80),
  "surname" varchar(150),
  "username" varchar(150),
  "email" varchar UNIQUE,
  "slug" varchar(50),
  "birthdate" timestamp,
  "avatar_url" varchar,
  "status" user_status,
  "is_verified" boolean,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "tweet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "content" varchar(150),
  "slug" varchar(50),
  "thumbnail_url" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "reply" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int,
  "user_id" int,
  "content" text,
  "parent_reply_id" int,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "follow" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "followed" int,
  "follower" int,
  "is_silence" boolean,
  "created_at" timestamp DEFAULT 'now()'
);

ALTER TABLE "tweet" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "reply" ADD FOREIGN KEY ("post_id") REFERENCES "tweet" ("id");

ALTER TABLE "reply" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "reply" ADD FOREIGN KEY ("parent_reply_id") REFERENCES "reply" ("id");

ALTER TABLE "follow" ADD FOREIGN KEY ("followed") REFERENCES "user" ("id");

ALTER TABLE "follow" ADD FOREIGN KEY ("follower") REFERENCES "user" ("id");
