
-- Serial
-- Es una secuencia 1, 2, 3, 4

CREATE TABLE "users" (
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR
);

-- Identity
-- Podemos especificar cualquier tipo de dato, no solo INTEGER
CREATE TABLE "users2" (
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"username" VARCHAR
);

-- Identity
-- Podemos especificar cualquier tipo de dato, no solo INTEGER
-- Nos permite forzar que nadie nos pueda insertar un ID de manera manual (Poniendo el ALWAYS)
-- Podemos modificar la secuencia no solo de 1 en 1 si no tambien 2 en 2
CREATE TABLE "users3" (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"username" VARCHAR
);

CREATE TABLE "users4" (
	"user_id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 2),
	"username" VARCHAR
);